summary = """Software engineer with expertise in C++ and Qt, experienced in both Automotive and Fintech domains.
Passionate about Rust, Linux, and shell scripting, with a strong ability to optimize workflows and build efficient, scalable systems.
Eager to contribute to innovative projects, grow professionally, and take on new challenges in a collaborative environment."""

interests = [
  "Customize GNU/Linux's desktop environment.",
  "Learn to design PCB and develop firmware in free time.",
]

[contact_info]
fullname = "Luu Hoang Kien"
title = "Software Developer"
email = "kien.luuhoang.arch@outlook.com"
website = "cv.lulkien.cc"
github = "lulkien"
linkedin = "kienlh-dev"
phone = "+84988449631"
location = "Hanoi, Vietnam"

[[education]]
institution = "University of Engineering and Technology"
degree = "Bachelor degree"
area_of_study = "Electronic and Telecommunication"
date_range = "September 2016 - October 2020"

[[skills]]
name = "C++"
description = "4+ years of C++ experience in automotive and fintech industries."

[[skills]]
name = "Rust"
description = "Rust hobbyist, learning through open-source contributions and personal projects."

[[skills]]
name = "Qt Framework"
description = "4+ years of Qt framework experience, primarily in automotive applications."

[[skills]]
name = "GNU/Linux"
description = "Linux user in professional and personal projects, homelab enthusiast with solid hands-on experience."

[[skills]]
name = "Shell scripting"
description = "Experienced in shell scripting, creating tools for work and personal projects."

[[projects]]
name = "SNaviBox"
date_range = "May 2024 - June 2024"
description = "Maintain and enhance the car navigation system for a major Japanese client."
highlights = [
  "Utilize expertise in automotive software and customer-specific requirements.",
  "Collaborate with cross-functional teams to implement new features and improvements.",
]

[[projects]]
name = "POIP.Cluster"
date_range = "January 2024 - March 2024"
description = """Develop a HMI layer for the cluster of a new luxury car model that will be on the market in the near future."""
highlights = ["Developed Charging Manager application."]

[[projects]]
name = "Cockpit2024"
date_range = "July 2023 - December 2023"
description = "Develop the applications for the new Cockpit system that was exhibited at CES2024."
highlights = [
  "Developed Navigation Application.",
  "Developed Media Player.",
  "Integrated text-to-speech feature.",
  "Configured Linux environment.",
  "Automated build and release process with shell scripting.",
]

[[projects]]
name = "Gen5.Premium"
date_range = "December 2020 - June 2023"
description = "Maintain HMI layer applications for an automotive AVN system for high-end cars."
highlights = [
  "Maintained and implemented new features for Home Screen Application.",
  "Elevated the user experience of the Settings Application by revamping and optimizing the search function.",
  "Provide solutions to problems for other features.",
]

[[projects]]
name = "Sonant"
date_range = "Ongoing"
website = "https://github.com/lulkien/sonant"
description = "Sonant is a simple C++ wrapper for recording audio with ALSA and transcribing with Whisper.cpp library."

[[languages]]
name = "Vietnamese"
description = "Native"

[[languages]]
name = "English"
description = "General Proficiency"
